.TH ENDURANCE-EXTRACT-PROCESS-SMAPS 1 "2011-03-04" "sp-endurance"
.SH NAME
endurance-extract-process-smaps - extract given process SMAPS information
.SH SYNOPSIS
endurance-extract-process-smaps <\fIprocess name\fP> [\fIdirectories\fP]
.SH DESCRIPTION
\fIendurance-extract-process-smaps\fP extracts the SMAPS data for given
process from the endurance data.  The extracted files can then be diffed
to find out more details about what in the SMAPS reported memory usage
actually changed (heap, stack, memory maps...).
.PP
The tool needs either to be run in the saved endurance data dir or
the endurance snapshot data dirs should be given to it.
.SH EXAMPLES
Usage examples:
.br
	endurance-extract-process-smaps pulseaudio
.br
	endurance-extract-process-smaps pulseaudio 120 121
.SH SEE ALSO
.IR endurance-parse-snapshots (1),
.IR endurance-report (1),
.IR sp_smaps_filter (1)
.SH COPYRIGHT
Copyright (C) 2009-2011 Nokia Corporation.
.PP
This is free software.  You may redistribute copies of it under the
terms of the GNU General Public License v2 included with the software.
There is NO WARRANTY, to the extent permitted by law.
