.TH ENDURANCE-SPLIT-SNAPSHOTS 1 "2009-10-26" "sp-endurance"
.SH NAME
endurance-split-snapshots - split endurance snapshots to separate reports
.SH SYNOPSIS
endurance-split-snapshots '\fIsplit points\fP'
\fIsnapshots directories\fP
.SH DESCRIPTION
\fIendurance-split-snapshots\fP splits the snapshots into
separate reports at indicated split points.  Typically
you use this tool if the normal endurance report indicates that
the device has re-booted between the snapshots as the resource
usage differences are not valid across re-boots.  The split point
numbers correspond to the test round numbers in the endurance report.
.SH EXAMPLE
A usage example:
.br
	endurance-split-snapshots '12 35 66' test-case/[0-9]*
.SH SEE ALSO
.IR endurance-snapshot (1),
.IR endurance-parse-snapshots (1)
.SH COPYRIGHT
Copyright (C) 2007-2009 Nokia Corporation.
.PP
This is free software.  You may redistribute copies of it under the
terms of the GNU General Public License v2 included with the software.
There is NO WARRANTY, to the extent permitted by law.
