.TH ENDURANCE-PARSE-SNAPSHOTS 1 "2009-10-26" "sp-endurance"
.SH NAME
endurance-parse-snapshots - produce HTML summary from the endurance snapshots
.SH SYNOPSIS
endurance-parse-snapshots [options] \fIdir1\fP [ \fIdir2\fP ... ]
.SH DESCRIPTION
\fIendurance-parse-snapshots\fP post-processes endurance snapshots
into an overview HTML report.  For instructions on how the whole process
of taking the snapshots and processing them works, see the README
file coming with these tools.
.SH OPTIONS
.TP
\fB--report\fP=\fIfilename\fP
Set the output report file name (default='endurance-report').
.TP
\fB--start-at\fP=\fIX\fP
Start parsing from Xth given snapshot directory (X > 0, default=0).
.TP
\fB--skip\fP=\fIN\fP
Skip N / parse only every (N+1)th snapshot (N > 0, default=0).
Use  this to see the resource usage changes more clearly.
.IP
Note that if you skip snapshots and you have cleared syslog between
them, the endurance report will miss all the sysloggeg errors from
the skipped snapshots.
.TP
\fB--stop-at\fP=\fIN\fP
Stop at Nth snapshot (by default all files are parsed).
.TP
\fB--stop-at-reboot\fP
Stop parsing if device had rebooted next round.
.TP
\fB--split-at-reboots\fP
Split results to separate report on reboot
(by default all snapshots go to same report).
.TP
\fB--parse-smaps\fP
Parse SMAPS details for all reports
(by default not parsed as it's very slow).
.PP
If you want more detailed SMAPS report from some specific test round
without using the slow '--parse-smaps' option for all the rounds,
install \fIsp-smaps-visualize\fP package and run these directly:
.br
	sp_smaps_analyze smaps.cap
.SH EXAMPLES
Normal usage:
.br
	endurance-parse-snapshots test-case/[0-9]*
.PP
Example of using most of the options:
.br
	endurance-parse-snapshots --report=report --start-at=3--skip=3\\
.br
	  --parse-smaps --split-at-reboots test-case/[0-9]*
.SH SEE ALSO
.IR endurance-snapshot (1),
.IR endurance-extract-process-smaps (1),
.IR endurance-split-snapshots (1),
.IR endurance-report (1),
.IR endurance-plot (1),
.IR sp_smaps_filter (1)
.SH COPYRIGHT
Copyright (C) 2007-2009 Nokia Corporation.
.PP
This is free software.  You may redistribute copies of it under the
terms of the GNU General Public License v2 included with the software.
There is NO WARRANTY, to the extent permitted by law.
