.TH ENDURANCE-PLOT 1 "2012-06-11" "sp-endurance"
.SH NAME
endurance-plot \- generate graphical representation of endurance data for trend analysis
.SH SYNOPSIS
endurance-plot \fIdir1\fP \fIdir2\fP ...
.SH DESCRIPTION
\fIendurance-plot\fP creates a large variety of (RAM, swap, CPU, X resource
usage, interrupt, context switch etc) graphs from sp-endurance collected data
for trend analysis. \fIendurance-plot\fP processes the given directories
(\fIdir1\fP, \fIdir2\fP, ...), and creates index.html and a collection of PNG
figures and corresponding jpeg thumbnails. The HTML file is placed in the
current working directory, and the figures are placed in a directory
\fIgraphs/\fP. Graph data and metadata is written in JSON format to file
index.json.
.PP
The HTML can be published by copying the graphs/ directory, index.html and
endurance-report.html into a browsable directory. \fIendurance-plot\fP
automatically adds a link to endurance-report.html to the resulting index.html
file. The endurance-report.html file is generated with endurance-report.
.PP
.B NOTE:
It's important that the snapshot directories are given in the same order as
in which the snapshots are done, otherwise the differences shown between the
snapshots are incorrect. It's OK to give a subset of the directories though.
The snapshot data is from \fIendurance-snapshot\fP.
.SH EXAMPLES
Normal usage:
.br
	endurance-plot endurance/*
.PP
Display results in web browser:
.br
	firefox index.html
.PP
Display results in graphics viewer:
.br
	display graphs/*.png
.PP
Optimize PNG files for size:
.br
	optipng graphs/*.png
.PP
.SH BUGS
endurance-plot can choke on some new input data, typically on special
characters that it tries to use as part of file names.
.SH SEE ALSO
.IR proc2csv (1),
.IR endurance-parse-snapshots (1),
.IR endurance-snapshot (1),
.IR gnuplot (1),
.IR optipng (1)
.SH COPYRIGHT
Copyright (C) 2010-2012 Nokia Corporation.
.PP
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License v2 included with the software.
There is NO WARRANTY, to the extent permitted by law.
