.TH EXTRACT-ENDURANCE-PROCESS-SMAPS 1 "2009-10-26" "sp-endurance"
.SH NAME
extract-endurance-process-smaps - extract given process SMAPS information
.SH SYNOPSIS
extract-endurance-process-smaps <\fIprocess name\fP>
.SH DESCRIPTION
\fIextract-endurance-process-smaps\fP extracts the SMAPS data for given
process from the endurance data.  The extracted files can then be diffed
to find out more details about what in the SMAPS reported memory usage
actually changed (heap, stack, memory maps...).
.PP
The tool needs to be run in the saved endurance data dir.
.SH EXAMPLES
Usage example:
.br
	extract-endurance-process-smaps pulseaudio
.SH SEE ALSO
.IR parse-endurance-measurements (1),
.IR endurance_report.py (1),
.IR sp_smaps_filter (1)
.SH COPYRIGHT
Copyright (C) 2009 Nokia Corporation.
.PP
This is free software.  You may redistribute copies of it under the
terms of the GNU General Public License v2 included with the software.
There is NO WARRANTY, to the extent permitted by law.
