.TH SP-COPY-NONCACHED 1 "2011-11-07" "sp-endurance"
.SH NAME
sp-copy-noncached - copies a file with minimal effect to kernel
page cache.
.SH SYNOPSIS
sp-save-noncached [<options>] <filein> <fileout>
.SH DESCRIPTION
\fIsp-save-noncached\fP utility copies files <filein> to <fileout>
without keeping data cached. Standard input/output
streams are used if '-' is specified as an input/output file names.

This utility was craeted to avoid "poisoning" the kernel page cache
when writing collected system endurance data into a file.
.TP
\fB-z\fP
Invoke lzop packer to compress the input file.
.SH OPTIONS
.TP
\fB-h\fP
Inline help page.
.SH SEE ALSO
.SH COPYRIGHT
Copyright (C) 2011 Nokia Corporation.
.PP
This is free software.  You may redistribute copies of it under the
terms of the GNU General Public License v2 included with the software.
There is NO WARRANTY, to the extent permitted by law.
