.TH SP-NONCACHED 1 "2011-11-07" "sp-endurance"
.SH NAME
sp-noncached - reads/writes files with a minimal effect to kernel
page cache.
.SH SYNOPSIS
sp-noncached -(w|r) <file1> [<file2>...]
.SH DESCRIPTION
\fIsp-noncached\fP utility reads/writes files into/from standard 
output/input without keeping data cached. 

This utility was craeted to avoid "poisoning" the kernel page cache
when writing collected system endurance data into a file.
.SH OPTIONS
.TP
\fB-r\fP (\fB--read\fP)
Reads from files <file1>, <file2> into standard output.
.TP
\fB-w\fP (\fB--write\fP) 
Writes standard input into <file1>.
.TP
\fB-h\fP
Inline help page.
.SH SEE ALSO
.SH COPYRIGHT
Copyright (C) 2011 Nokia Corporation.
.PP
This is free software.  You may redistribute copies of it under the
terms of the GNU General Public License v2 included with the software.
There is NO WARRANTY, to the extent permitted by law.
