.TH SUM-SMAPS-PRIVATE 1 "2007-04-04" "sp-endurance"
.SH NAME
sum-smaps-private - show private memory usage of given process
.SH SYNOPSIS
sum-smaps-private \fIPID\fP
.SH DESCRIPTION
\fIsum-smaps-private\fP outputs the given process private memory usage.
This information is parsed from the /proc/PID/smaps file.
.SH SEE ALSO
.IR sum-dirty-code-pages (1)
.SH COPYRIGHT
Copyright (C) 2007 Nokia Corporation.
.PP
This is free software.  You may redistribute copies of it under the
terms of the GNU General Public License v2 included with the software.
There is NO WARRANTY, to the extent permitted by law.
