#!/bin/sh
#
# Extract given process SMAPS data from sp-endurance smaps.cap.lzo files.
# This file is part of sp-endurance.
#
# Copyright (C) 2009-2011 by Nokia Corporation
#
# Contact: Eero Tamminen <eero.tamminen@nokia.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 
# version 2 as published by the Free Software Foundation. 
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02110-1301 USA

usage ()
{
	name=${0##*/}
	echo
	echo "usage:"
	echo "	$name <program name> [directories]"
	echo 
	echo "This can be run in the saved endurance data dir to extract"
	echo "SMAPS information for the named process(es). Or you can give"
	echo "the endurance snapshot directories from which it should"
	echo "extract the informations."
	echo
	echo "Examples:"
	echo "	$name pulseaudio"
	echo "	$name pulseaudio 120 121"
	echo
	echo "ERROR: $1!"
	echo
	exit 1
}

if [ -z "$(which lzop)" ]; then
	usage "'lzop' utility to extract SMAPS .lzo content is missing"
fi

prog=$1
if [ -z "$prog" ]; then
	usage "Give a name for program which info should be extracted"
fi
if [ "$prog" = "-h" ] || [ "$prog" = "--help" ]; then
	usage "-h/--help given as program name"
fi
shift

echo "Searching/extracting SMAPS information for '$prog' from snapshots..."

extract_info ()
{
	# get snapshot/directory name/number
	num=${1%/*}
	num=${num##*/}
	name=$prog-$num.cap
	echo "- $num"
	# uncompress, take only program info and store that
	lzop -c -d $1 | awk "
/^==/ {	show=0; next }
/Name: $prog/ {	show=1 }
{ if(show) print }" > $name
}

capfile=smaps.cap.lzo

if [ $# -gt 0 ]; then
	for dir in $*; do
		if [ \! -d "$dir" ]; then
			usage "Given snapshot directory '$dir' doesn't exist"
		fi
		if [ \! -f "$dir/$capfile" ]; then
			usage "Given snapshot directory '$dir' doesn't have '$capfile' SMAPS capture file"
		fi
	done
	for dir in $*; do
		extract_info $dir/$capfile
	done
else
	if [ \! -f 101/$capfile ]; then
		usage "Endurance SMAPS files like '101/smaps.cap.lzo' are missing"
	fi
	for file in */$capfile; do
		extract_info $file
	done
fi

fgrep -q "Name: $prog" $prog-*.cap
if [ $? -ne 0 ]; then
	echo "ERROR: No matches found for program '$prog'!" 1>&2
	rm $prog-*.cap
	exit 1
fi
echo "Information extracted:"
ls $prog-*.cap
